import type { DeepResearchReport } from '../services/deepResearchEngine';

interface ResearchReportModalProps {
  isOpen: boolean;
  report: DeepResearchReport | null;
  onClose: () => void;
}

export function ResearchReportModal({ isOpen, report, onClose }: ResearchReportModalProps) {
  if (!isOpen || !report) return null;

  const exportMarkdown = () => {
    let md = `# Deep Research Report: ${report.topic}\n\n`;
    md += `*Generated by Nova Deep Research Engine on ${new Date(report.generatedAt).toLocaleString()}*\n\n`;
    md += `## Executive Summary\n${report.summary}\n\n`;

    report.sections.forEach(sec => {
      md += `### ${sec.heading}\n${sec.body}\n\n`;
      if (sec.citations.length > 0) {
        md += `*Citations:* ${sec.citations.join(', ')}\n\n`;
      }
    });

    md += `## Authoritative Sources\n`;
    report.sources.forEach(src => {
      md += `- [${src.title}](${src.url}) (Credibility: ${src.credibilityScore}%)\n  *${src.snippet}*\n\n`;
    });

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `research-report-${report.topic.toLowerCase().replace(/\s+/g, '-')}.md`;
    a.click();
  };

  return (
    <div className="modal-backdrop" onClick={onClose}>
      <div className="research-modal-card" onClick={e => e.stopPropagation()}>
        <div className="modal-header">
          <div className="modal-title">
            <span className="icon">🔬</span>
            <span>DEEP RESEARCH REPORT</span>
          </div>
          <button className="close-btn" onClick={onClose}>✕</button>
        </div>

        <div className="modal-body research-body">
          <div className="report-topic-header">
            <h2>{report.topic}</h2>
            <span className="report-date">
              Synthesized on {new Date(report.generatedAt).toLocaleDateString()}
            </span>
          </div>

          <div className="report-summary-box">
            <h4>EXECUTIVE SUMMARY</h4>
            <p>{report.summary}</p>
          </div>

          {report.sections.map((sec, idx) => (
            <div key={idx} className="report-section-block">
              <h3>{sec.heading}</h3>
              <p>{sec.body}</p>
              {sec.citations.length > 0 && (
                <div className="section-citations">
                  <span>🔗 Cited Sources: </span>
                  {sec.citations.map((c, i) => (
                    <a key={i} href={c} target="_blank" rel="noopener noreferrer" className="citation-link">
                      [{i + 1}] {c}
                    </a>
                  ))}
                </div>
              )}
            </div>
          ))}

          <div className="report-sources-list">
            <h3>AUTHORITATIVE SOURCES ({report.sources.length})</h3>
            {report.sources.map((src, idx) => (
              <div key={idx} className="source-card">
                <div className="source-title-row">
                  <a href={src.url} target="_blank" rel="noopener noreferrer" className="source-link">
                    {src.title}
                  </a>
                  <span className="credibility-badge">{src.credibilityScore}% Credibility</span>
                </div>
                <p className="source-snippet">{src.snippet}</p>
              </div>
            ))}
          </div>
        </div>

        <div className="modal-footer">
          <button className="sec-action-btn" onClick={exportMarkdown}>
            📥 Export Report (.md)
          </button>
          <button className="primary-modal-btn" onClick={onClose}>
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
